// Typed accessors over the bundled EVE Static Data Export (SDE) JSON.
// Generated by scripts/generate-sde.mjs. These are NPC stations and solar
// systems only — player-owned structures (citadels) require an authenticated
// ESI call and are resolved/handled separately.
import rawStations from './stations.json';
import rawSystems from './systems.json';

export interface Station {
  id: number;
  name: string;
  systemId: number;
}

export interface SolarSystem {
  id: number;
  name: string;
  /** Truescaled security status, rounded to 2 decimals (-1.0 .. 1.0). */
  security: number;
}

export const stations = rawStations as Station[];

// systems.json is a compact map: { [systemId]: [name, security] }.
const systemsRaw = rawSystems as unknown as Record<string, [string, number]>;

const stationById = new Map<number, Station>(stations.map((s) => [s.id, s]));

const systemById = new Map<number, SolarSystem>(
  Object.entries(systemsRaw).map(([id, [name, security]]) => [
    Number(id),
    { id: Number(id), name, security },
  ]),
);

export function getStation(id: number): Station | undefined {
  return stationById.get(id);
}

export function getSystem(id: number): SolarSystem | undefined {
  return systemById.get(id);
}

/** Security bucket used for colouring and route descriptions. */
export type SecurityBand = 'high' | 'low' | 'null';

export function securityBand(security: number): SecurityBand {
  if (security >= 0.45) return 'high';
  if (security > 0.0) return 'low';
  return 'null';
}

/**
 * Case-insensitive substring search over NPC station names.
 * Returns prefix matches first, then other substring matches, capped.
 */
export function searchStations(query: string, limit = 50): Station[] {
  const q = query.trim().toLowerCase();
  if (q.length < 3) return [];

  const prefix: Station[] = [];
  const contains: Station[] = [];
  for (const station of stations) {
    const name = station.name.toLowerCase();
    if (name.startsWith(q)) {
      prefix.push(station);
    } else if (name.includes(q)) {
      contains.push(station);
    }
    if (prefix.length >= limit) break;
  }
  return [...prefix, ...contains].slice(0, limit);
}
